host: https://cb2d8bc9-0ee0-4-231-b9ee.documents.azure.com:443/
master_key: vcERObAL0vqUCMFdxdmIxj7FGpSwiiMYuX4zTmVnxmI1EYhedMLA2J4jwW7WT3FuEbQC06huaMRaACDbgsTy7g==
database_id: SampleDB
container_id: Units